"use client";
import * as React from "react";
import { AlertTriangle, ExternalLink, Lightbulb, Route, ShieldCheck, Target } from "lucide-react";
import { AgentLoading } from "./agent-loading";
import type { ResearchCampaignPlan, ResearchDecision, ResearchEvidence } from "@/types/research";

interface Props { plan: ResearchCampaignPlan | null; isLoading: boolean; error: string | null; onRetry: () => void }
type Tab = "positioning" | "routes" | "sources";
const steps = ["Exa tìm nguồn thị trường...", "Đọc và kiểm chứng nguồn...", "Phân tích định vị và creative routes...", "Kiểm định evidence và hoàn thiện campaign plan..."];

function EvidenceList({ evidence }: { evidence: ResearchEvidence[] }) {
  return <div className="space-y-2">{evidence.map((item, index) => <div key={`${item.basis}-${index}`} className="p-3 border border-foreground/10 bg-background/40 text-xs font-mono"><div className="text-[#35ea52] uppercase tracking-wider mb-1">{item.basis}</div><p className="text-foreground/60 leading-relaxed">{item.detail}</p>{item.source_url && <a href={item.source_url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-foreground/40 hover:text-foreground"><ExternalLink className="h-3 w-3" />Mở nguồn</a>}</div>)}</div>;
}
function DecisionCard({ title, decision }: { title: string; decision: ResearchDecision }) {
  return <article className="p-5 border border-foreground/10 bg-foreground/[0.02] space-y-4"><h3 className="text-xs font-mono font-bold text-[#35ea52] tracking-widest uppercase">{title}</h3><p className="text-base font-semibold text-foreground leading-relaxed">{decision.decision}</p><p className="text-sm font-mono text-foreground/55 leading-relaxed">{decision.rationale}</p><EvidenceList evidence={decision.evidence} /></article>;
}

export const StageResearch: React.FC<Props> = ({ plan, isLoading, error, onRetry }) => {
  const [tab, setTab] = React.useState<Tab>("positioning");
  if (isLoading) return <div className="h-full flex flex-col justify-center max-w-xl mx-auto w-full"><AgentLoading agentName="TÁC_TỬ_NGHIÊN_CỨU_TỔNG" steps={steps} isComplete={false} /></div>;
  if (error) return <div className="min-h-[420px] flex items-center justify-center"><div className="max-w-lg text-center space-y-4"><AlertTriangle className="h-9 w-9 text-red-400 mx-auto" /><h2 className="font-mono font-bold">NGHIÊN CỨU THẤT BẠI</h2><p className="text-sm font-mono text-foreground/50">{error}</p><button type="button" onClick={onRetry} className="px-5 py-2 border border-foreground text-xs font-mono hover:bg-foreground hover:text-background">THỬ LẠI</button></div></div>;
  if (!plan) return <div className="min-h-[420px] flex items-center justify-center text-sm font-mono text-foreground/35">Chưa có kế hoạch chiến dịch. Hãy quay lại và gửi thông tin nghiên cứu.</div>;

  const positioning = plan.product_positioning;
  return <div className="space-y-6 h-full flex flex-col animate-in fade-in duration-500">
    <div className="space-y-4 border-b border-foreground/10 pb-4"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold font-mono tracking-wider text-foreground">PHÂN TÍCH & NGHIÊN CỨU</h2><p className="text-sm font-mono text-foreground/40 mt-1">Lược đồ kế hoạch phiên bản {plan.schema_version} · dữ liệu trực tiếp từ hệ thống nghiên cứu</p></div><ShieldCheck className="h-6 w-6 text-[#35ea52]" /></div><div className="flex flex-wrap gap-2">{([['positioning','ĐỊNH VỊ'],['routes','HƯỚNG SÁNG TẠO'],['sources','NGUỒN & GIẢ ĐỊNH']] as const).map(([id,label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`px-4 py-2 text-xs font-mono font-bold tracking-widest border ${tab === id ? 'bg-[#35ea52] text-black border-[#35ea52]' : 'text-foreground/50 border-foreground/10'}`}>{label}</button>)}</div></div>
    <div className="flex-1 overflow-y-auto pb-6">
      {tab === "positioning" && <div className="space-y-5"><DecisionCard title="Main campaign angle" decision={positioning.main_campaign_angle} /><DecisionCard title="Target audience" decision={positioning.target_audience} /><DecisionCard title="Key selling message" decision={positioning.key_selling_message} /><section className="space-y-3"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-[#35ea52]" /><h3 className="text-xs font-mono font-bold tracking-widest">BENEFIT HIERARCHY</h3></div>{[...positioning.benefit_hierarchy].sort((a,b) => a.rank-b.rank).map((item) => <article key={item.rank} className="p-4 border border-foreground/10"><div className="flex gap-4"><span className="text-2xl font-mono text-[#35ea52]">{item.rank}</span><div className="space-y-2"><h4 className="font-semibold">{item.benefit}</h4><p className="text-sm font-mono text-foreground/50 leading-relaxed">{item.rationale}</p></div></div></article>)}</section></div>}
      {tab === "routes" && <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">{plan.creative_routes.map((route) => <article key={route.route_name} className="p-5 border border-foreground/10 space-y-4"><div className="flex items-center gap-2"><Route className="h-4 w-4 text-[#35ea52]" /><h3 className="font-mono font-bold text-[#35ea52]">{route.route_name}</h3></div><div><span className="text-[10px] font-mono text-foreground/35">HOOK</span><p className="font-semibold mt-1">{route.hook_idea}</p></div><div><span className="text-[10px] font-mono text-foreground/35">VISUAL DIRECTION</span><p className="text-sm text-foreground/60 mt-1">{route.visual_direction}</p></div><div><span className="text-[10px] font-mono text-foreground/35">MESSAGE ANGLE</span><p className="text-sm text-foreground/60 mt-1">{route.message_angle}</p></div><div className="flex flex-wrap gap-2">{route.suggested_platform_usage.map((platform) => <span key={platform} className="px-2 py-1 border border-foreground/15 text-[10px] font-mono">{platform}</span>)}</div><p className="text-xs font-mono text-foreground/45 leading-relaxed">{route.rationale}</p><EvidenceList evidence={route.evidence} /></article>)}</div>}
      {tab === "sources" && <div className="space-y-6"><section className="space-y-3">{plan.source_summary.sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="block p-4 border border-foreground/10 hover:border-[#35ea52]/40"><div className="flex items-start justify-between gap-4"><h3 className="font-semibold text-sm">{source.title}</h3><ExternalLink className="h-4 w-4 shrink-0 text-[#35ea52]" /></div></a>)}</section><section className="p-5 border border-amber-500/20 bg-amber-500/5"><div className="flex items-center gap-2 mb-3"><Lightbulb className="h-4 w-4 text-amber-400" /><h3 className="text-xs font-mono font-bold text-amber-400 tracking-widest">ASSUMPTIONS TO VERIFY</h3></div><ul className="space-y-2">{plan.source_summary.assumptions.map((item,index) => <li key={index} className="text-sm font-mono text-foreground/55">• {item}</li>)}</ul></section></div>}
    </div>
  </div>;
};
